# Generated by Django 3.2.4 on 2021-06-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('type_of_search', models.CharField(choices=[('contains', 'Default(contains the pattern)'), ('match_in', 'In(includes a whole word)'), ('match_out', 'Out(excludes a whole word)')], default='Default', max_length=20)),
                ('pattern', models.CharField(max_length=100)),
                ('column', models.CharField(max_length=50)),
                ('brands', models.ManyToManyField(related_name='rules', to='api.Brand')),
            ],
        ),
    ]
